version = 0.1
[default.deploy.parameters]
stack_name = "products-microservice"
resolve_s3 = true
s3_prefix = "products-microservice"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "LambdaAuthorizerArn=\"arn:aws:lambda:us-east-1:968225077300:function:lambda-authorizer-ApiFunction-ChSGvdaJ8S0g\" TagEnvironment=\"production\" TagProject=\"devops-na-nuvem-serverless-workshop\""
image_repositories = []
