AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  TagEnvironment: 
    Type: String
    Default: production
    Description: Environment Type.
  TagProject:
    Type: String
    Default: devops-na-nuvem-serverless-workshop
    Description: Project Name.

Resources:

  ApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: python3.12
      Handler: authorizer.lambda_handler
      Timeout: 30
      Policies:
      - AWSLambdaBasicExecutionRole
      Environment:
        Variables:
          COGNITO_USER_POOL_ID: !Ref CognitoUserPool
          COGNITO_REGION: !Ref AWS::Region
          COGNITO_ISSUER: !Sub https://cognito-idp.${AWS::Region}.amazonaws.com/${CognitoUserPool}
      Tags:
        Project: !Ref TagProject
        Environment: !Ref TagEnvironment

  CognitoUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: serverless-workshop-pool
      Policies:
        PasswordPolicy:
          MinimumLength: 8
      UsernameAttributes:
        - email
      Schema:
        - AttributeDataType: String
          Name: email
          Required: false
  
  CognitoUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      UserPoolId: !Ref CognitoUserPool
      ClientName: serverless-workshop-pool-client
      GenerateSecret: false
      ExplicitAuthFlows:
        - ALLOW_USER_PASSWORD_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH