version = 0.1
[default.deploy.parameters]
stack_name = "lambda-authorizer"
resolve_s3 = true
s3_prefix = "lambda-authorizer"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "TagEnvironment=\"production\" TagProject=\"devops-na-nuvem-serverless-workshop\""
image_repositories = []
